#configFile="" #Your config.toml profile directory
#appDataDir="" # Your DB storage path
#logDir="" # log path
#network="mainnet" #network mainnet,testnet,privnet default testnet
network="testnet"
#Qitmeerd
#QServer=
#QUser=
#QPass=
QNoTLS=true
QTLSSkipVerify=true
#WalletPass="public" #Wallet encryption code default public

#web model
#listeners=["127.0.0.1:8130"]
#rpcUser=""
#rpcPass=""
#ui=true