#configFile=""
#appDataDir=""
#debugLevel=""
#logDir=""

network="testnet"
#Listeners=[127.0.0.1:8132]
#ApiUrl=127.0.0.1:8132
#ui=false
#RPCUser=""
#RPCPass=""
#RPCCert=""
#RPCKey=""
#RPCMaxClients=10
#DisableRPC=false
#DisableTLS=false

#Qitmeerd
QServer="47.88.220.44:8131"
QUser="admin"
QPass="123456"
#QCert=""
QNoTLS=true
#QTLSSkipVerify =false
#QProxy     =""
#QProxyUser =""
#QProxyPass =""

WalletPass="public"