#configFile="" #Your config.toml profile directory
#appDataDir="" # Your DB storage path
#logDir="" # log path

#network="mainnet" #network mainnet,testnet,privnet default mainet
#network="testnet"
#network="privnet"

#Qitmeerd
QServer="47.88.220.44:8131"
QUser="admin"
QPass="123456"

WalletPass="public" #Wallet encryption code default public