#configFile="" #Your config.toml profile directory
#appDataDir="" # Your DB storage path
#logDir="" # log path
#network="mainnet" #network mainnet,testnet,privnet default testnet
network="testnet"
#network="privnet"
#Qitmeerd
QServer="47.88.220.44:8131"
QUser="admin"
QPass="123456"
#WalletPass="public" #Wallet encryption code default public
#listeners=["127.0.0.1:8130"]
#rpcUser="admin"
#rpcPass="123"
#ui=true